version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432

  nginx:
    image: nginx:latest
    ports:
      - 8000:8000
    volumes:
      - ./static:/static
      - ./conf/nginx-docker.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    command: [nginx-debug, '-g', 'daemon off;']

  web:
    image: 63phc/web
    command: python3 manage.py makemigrations
    command: python3 manage.py migrate
    command: gunicorn core.wsgi:application -w 2 -b :8000
    volumes:
      - .:/project
    expose:
      - "8000"
    depends_on:
      - db


